#!/bin/bash
exec 2>&1

PGDATA=/var/lib/postgresql/data

chown postgres:postgres "$PGDATA"
chmod 0700 "$PGDATA"

if [ ! -f "$PGDATA/PG_VERSION" ]; then
    su postgres -c "/usr/lib/postgresql/17/bin/initdb -D $PGDATA"
fi

exec su postgres -c "/usr/lib/postgresql/17/bin/postgres -D $PGDATA -c listen_addresses=127.0.0.1 -c max_connections=200"
