#!/bin/bash
exec 2>&1

cd /app
if [ -n "$OTEL_EXPORTER_OTLP_ENDPOINT" ]; then
  exec /root/.bun/bin/bun run services/cron/dist/index.js | /root/.bun/bin/bun packages/log-transport/src/index.ts
else
  exec /root/.bun/bin/bun run services/cron/dist/index.js
fi
