const KEEPER_API_READ_SCOPE = "keeper.read";
const KEEPER_API_SOURCE_SCOPE = "keeper.sources.read";
const KEEPER_API_DESTINATION_SCOPE = "keeper.destinations.read";
const KEEPER_API_MAPPING_SCOPE = "keeper.mappings.read";
const KEEPER_API_EVENT_SCOPE = "keeper.events.read";
const KEEPER_API_SYNC_SCOPE = "keeper.sync-status.read";

const KEEPER_API_SCOPES = [
  KEEPER_API_READ_SCOPE,
  KEEPER_API_SOURCE_SCOPE,
  KEEPER_API_DESTINATION_SCOPE,
  KEEPER_API_MAPPING_SCOPE,
  KEEPER_API_EVENT_SCOPE,
  KEEPER_API_SYNC_SCOPE,
];

const KEEPER_API_RESOURCE_SCOPES = [...KEEPER_API_SCOPES];

const KEEPER_API_DEFAULT_SCOPE = ["offline_access", ...KEEPER_API_RESOURCE_SCOPES].join(" ");

export {
  KEEPER_API_DEFAULT_SCOPE,
  KEEPER_API_DESTINATION_SCOPE,
  KEEPER_API_EVENT_SCOPE,
  KEEPER_API_MAPPING_SCOPE,
  KEEPER_API_READ_SCOPE,
  KEEPER_API_RESOURCE_SCOPES,
  KEEPER_API_SCOPES,
  KEEPER_API_SOURCE_SCOPE,
  KEEPER_API_SYNC_SCOPE,
};
