const MS_PER_SECOND = 1000;
const SECONDS_PER_MINUTE = 60;
const MINUTES_PER_HOUR = 60;
const HOURS_PER_DAY = 24;
const DAYS_PER_WEEK = 7;
const REFRESH_BUFFER_MINUTES = 5;
const RATE_LIMIT_SECONDS = 60;

const MS_PER_MINUTE = SECONDS_PER_MINUTE * MS_PER_SECOND;
const MS_PER_HOUR = MINUTES_PER_HOUR * MS_PER_MINUTE;
const MS_PER_DAY = HOURS_PER_DAY * MS_PER_HOUR;
const MS_PER_WEEK = DAYS_PER_WEEK * MS_PER_DAY;

const SECONDS_PER_HOUR = MINUTES_PER_HOUR * SECONDS_PER_MINUTE;
const SECONDS_PER_DAY = HOURS_PER_DAY * SECONDS_PER_HOUR;

const TOOLTIP_CLEAR_DELAY_MS = 1500;
const TOAST_TIMEOUT_MS = 3000;
const WEBSOCKET_RECONNECT_DELAY_MS = 3000;
const TOKEN_TTL_MS = 30_000;
const TOKEN_REFRESH_BUFFER_MS = REFRESH_BUFFER_MINUTES * MS_PER_MINUTE;
const RATE_LIMIT_DELAY_MS = RATE_LIMIT_SECONDS * MS_PER_SECOND;
const SYNC_TTL_SECONDS = SECONDS_PER_DAY;

const KEEPER_EVENT_SUFFIX = "@keeper.sh";
const KEEPER_CATEGORY = "keeper.sh";

export {
  MS_PER_SECOND,
  MS_PER_MINUTE,
  MS_PER_HOUR,
  MS_PER_DAY,
  MS_PER_WEEK,
  SECONDS_PER_MINUTE,
  SECONDS_PER_HOUR,
  SECONDS_PER_DAY,
  TOOLTIP_CLEAR_DELAY_MS,
  TOAST_TIMEOUT_MS,
  WEBSOCKET_RECONNECT_DELAY_MS,
  TOKEN_TTL_MS,
  TOKEN_REFRESH_BUFFER_MS,
  RATE_LIMIT_DELAY_MS,
  SYNC_TTL_SECONDS,
  KEEPER_EVENT_SUFFIX,
  KEEPER_CATEGORY,
};
