const DEFAULT_FLUSH_WRITER_CONNECTIONS = 16;

const FLUSH_WRITER_CONNECTIONS = Number(
  process.env.CRON_FLUSH_POOL_MAX ?? DEFAULT_FLUSH_WRITER_CONNECTIONS,
);

export { FLUSH_WRITER_CONNECTIONS, DEFAULT_FLUSH_WRITER_CONNECTIONS };
