import type { PgTable } from "drizzle-orm/pg-core";
import {
  account,
  jwks,
  oauthAccessToken,
  oauthClient,
  oauthConsent,
  oauthRefreshToken,
  passkey,
  session,
  user,
  verification,
} from "./auth-schema";
import {
  apiTokensTable,
  caldavCredentialsTable,
  calendarAccountsTable,
  calendarPushChannelsTable,
  calendarRemovalsTable,
  calendarSnapshotsTable,
  calendarsTable,
  eventMappingsTable,
  eventStatesTable,
  feedbackTable,
  icalFeedCalendarsTable,
  icalFeedSettingsTable,
  icalFeedsTable,
  oauthCredentialsTable,
  sourceDestinationMappingsTable,
  syncStatusTable,
  userEventsTable,
  userSubscriptionsTable,
  userSyncRequestsTable,
} from "./schema";

const SCHEMA_TABLES: PgTable[] = [
  account,
  apiTokensTable,
  caldavCredentialsTable,
  calendarAccountsTable,
  calendarPushChannelsTable,
  calendarRemovalsTable,
  calendarSnapshotsTable,
  calendarsTable,
  eventMappingsTable,
  eventStatesTable,
  feedbackTable,
  icalFeedCalendarsTable,
  icalFeedSettingsTable,
  icalFeedsTable,
  jwks,
  oauthAccessToken,
  oauthClient,
  oauthConsent,
  oauthCredentialsTable,
  oauthRefreshToken,
  passkey,
  session,
  sourceDestinationMappingsTable,
  syncStatusTable,
  user,
  userEventsTable,
  userSubscriptionsTable,
  userSyncRequestsTable,
  verification,
];

export { SCHEMA_TABLES };
