const PRO_ACCOUNT_LIMIT = 2;
const UNLIMITED_ACCOUNT_LIMIT = Infinity;

const PRO_MAPPING_LIMIT = 3;
const UNLIMITED_MAPPING_LIMIT = Infinity;

export { PRO_ACCOUNT_LIMIT, UNLIMITED_ACCOUNT_LIMIT, PRO_MAPPING_LIMIT, UNLIMITED_MAPPING_LIMIT };
